// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnIt56xPRh_CTblbmhq5j6VXbV3qq49Go',
    appId: '1:545545369243:web:1fa9b2fd5e4176bf7cb83e',
    messagingSenderId: '545545369243',
    projectId: 'pmjay-live-audit',
    authDomain: 'pmjay-live-audit.firebaseapp.com',
    storageBucket: 'pmjay-live-audit.firebasestorage.app',
    measurementId: 'G-RGX6WZ96LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCORXpNPyn3GUyNC7Pw_58nxM7GyoiqSk0',
    appId: '1:545545369243:android:ff4a8f0bb54a8de07cb83e',
    messagingSenderId: '545545369243',
    projectId: 'pmjay-live-audit',
    storageBucket: 'pmjay-live-audit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJAjE16xRKeE1DicFLWwySoosNUhRZBxg',
    appId: '1:545545369243:ios:bb0c2f42c02b68327cb83e',
    messagingSenderId: '545545369243',
    projectId: 'pmjay-live-audit',
    storageBucket: 'pmjay-live-audit.firebasestorage.app',
    iosBundleId: 'com.example.pmjayLiveAuditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJAjE16xRKeE1DicFLWwySoosNUhRZBxg',
    appId: '1:545545369243:ios:bb0c2f42c02b68327cb83e',
    messagingSenderId: '545545369243',
    projectId: 'pmjay-live-audit',
    storageBucket: 'pmjay-live-audit.firebasestorage.app',
    iosBundleId: 'com.example.pmjayLiveAuditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnIt56xPRh_CTblbmhq5j6VXbV3qq49Go',
    appId: '1:545545369243:web:ab87b2488df894287cb83e',
    messagingSenderId: '545545369243',
    projectId: 'pmjay-live-audit',
    authDomain: 'pmjay-live-audit.firebaseapp.com',
    storageBucket: 'pmjay-live-audit.firebasestorage.app',
    measurementId: 'G-9C8NZ8NRXR',
  );
}
